### ISSUE TITLE
Weird node labels

### ISSUE THREAD

**Issue by tkchafin** [pomo-dev/PoMo#4]
There are weird node labels in my output tree (e.g. "7", "8", "8_1", "5"), and I cannot find out what these are. Also is there a way to assess node supports, like by bootstrapping? I have pasted my tree below. 

Thanks

((((((pop1:0.006967148011670597,(pop2:0.004659658067372647,pop3:0.004659658067372647)7:0.002307489944297949):9.48070498431786e-05,pop4:0.007061955061513775):0,pop5:0.007061955061513775):0.0002085704261265209,(((pop6:0.006187958204941432,pop7:0.006187958204941432)0:9.130371185829025e-05,pop8:0.006279261916799722)9:0.0001569480420176401,(pop9:0.004739396113684455,pop10:0.004739396113684455)8:0.001696813845132904)8_1:0.0008343155288229337):0.008828156305048273,(pop11:0.009464288953067437,pop12:0.009464288953067437)5:0.006634392839621126):0.001136257142998108,((pop13:0.002790136679691311,pop14:0.002790136679691311)7:0.00129245107529496,pop15:0.004082587754986269)0_1:0.01315235118070041);

**Comment by dschrempf** [comment]
Hello,

HyPhy seems to insert inner node labels automatically.  They are now removed at the end of program execution.  Node support values cannot be calculated with PoMo at the moment.  You could do a bootstrap analysis if you are very interested in this.

Best,
Dominik
